### PR TITLE
Add `django-stubs` to the list of projects

### PR DESCRIPTION
**Pull request by sobolevn**
Let's try it!

### CODE REVIEW

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
Hm, I think you'll need some sort of install command to install the plugin you want to use while checking django-stubs (possible just `install_cmd="{install} .",`)

**Comment by sobolevn** [comment]
@hauntsaninja how can I test that the whole intergration worked?

**Comment by sobolevn** [comment]
Thanks for the quick review and merge! ❤️

**Comment by hauntsaninja** [comment]
Yes, that'll work. I also just ran it locally before merging using `mypy_primer -k django-stub --debug --old v1.10.0`

**Comment by AlexWaygood** [comment]
Some strange resolution failure here when trying to install django-stubs: https://github.com/python/typeshed/actions/runs/10112015097/job/27965167268?pr=12433.

Hopefully just a fluke of some kind, I'll try rerunning

**Comment by sobolevn** [comment]
@flaeppe looks like our release is partially broken :(

**Comment by flaeppe** [comment]
I think we just need to make a release. We only prepared for one.

**Comment by sobolevn** [comment]
oh, I see then why it fails: we bumped the dependency in `git` and not release `ext@5.0.3`

**Comment by flaeppe** [comment]
But something seems quite off if we're installing `.` on `master` and run in to troubles. When installing in our CI, with `pip`, we set the env variable `SETUPTOOLS_ENABLE_FEATURES=legacy-editable` not sure if that affects anything

**Comment by andersk** [comment]
We need to install both `.` and `./ext`, not just `.`.

- #125

**Pull request merged**
