### PR TITLE
update cwltool/schema-salad setup to be more resiliant

### PR DESCRIPTION
**Pull request by mr-c**
`expected_mypy_success=True` as well

### CODE REVIEW

**Comment by mr-c** [comment]
Tested locally with `mypy_primer --debug --type-checker mypy -k common-workflow-language`

**Comment by mr-c** [comment]
This is ready for review and merging, thanks!

**Comment by A5rocks** [comment]
I'm not sure `grep` here is allowed because mypy-primer *should* (though it's kinda bad at it) be able to run on Windows.

**Review by hauntsaninja — COMMENTED** [review]
Thanks, would you mind marking it using the nice `supported_platforms` annotation A5rocks added in https://github.com/hauntsaninja/mypy_primer/pull/110/files

**Comment by mr-c** [comment]
@hauntsaninja Done, thank you!

**Review by hauntsaninja — APPROVED** [review]

**Pull request merged**
